version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "gunicorn", "main:app", "-k", "uvicorn.workers.UvicornWorker", "-w", "2", "-b", "0.0.0.0:8080", "--timeout", "120" ]
    env_file:
      - .env
    ports:
      - "${API_PORT:-8080}:8080"
