"""add: initial tables

Revision ID: 4982ce759014
Revises: 
Create Date: 2024-03-07 01:31:36.240357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4982ce759014'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text("now()")),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='financial'
    )
    op.create_table('acc_payable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_entity', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('cost', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text("now()")),
    sa.Column('status', sa.Boolean(), nullable=False, server_default=sa.text("true")),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_entity'),
    sa.ForeignKeyConstraint(['id_entity'], ['financial.entity.id']),
    schema='financial'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity', schema='financial')
    op.drop_table('acc_payable', schema='financial')
    # ### end Alembic commands ###
